################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../jpeg-9c/jaricom.c \
../jpeg-9c/jcapimin.c \
../jpeg-9c/jcapistd.c \
../jpeg-9c/jcarith.c \
../jpeg-9c/jccoefct.c \
../jpeg-9c/jccolor.c \
../jpeg-9c/jcdctmgr.c \
../jpeg-9c/jchuff.c \
../jpeg-9c/jcinit.c \
../jpeg-9c/jcmainct.c \
../jpeg-9c/jcmarker.c \
../jpeg-9c/jcmaster.c \
../jpeg-9c/jcomapi.c \
../jpeg-9c/jcparam.c \
../jpeg-9c/jcprepct.c \
../jpeg-9c/jcsample.c \
../jpeg-9c/jctrans.c \
../jpeg-9c/jdapimin.c \
../jpeg-9c/jdapistd.c \
../jpeg-9c/jdarith.c \
../jpeg-9c/jdatadst.c \
../jpeg-9c/jdatasrc.c \
../jpeg-9c/jdcoefct.c \
../jpeg-9c/jdcolor.c \
../jpeg-9c/jddctmgr.c \
../jpeg-9c/jdhuff.c \
../jpeg-9c/jdinput.c \
../jpeg-9c/jdmainct.c \
../jpeg-9c/jdmarker.c \
../jpeg-9c/jdmaster.c \
../jpeg-9c/jdmerge.c \
../jpeg-9c/jdpostct.c \
../jpeg-9c/jdsample.c \
../jpeg-9c/jdtrans.c \
../jpeg-9c/jerror.c \
../jpeg-9c/jfdctflt.c \
../jpeg-9c/jfdctfst.c \
../jpeg-9c/jfdctint.c \
../jpeg-9c/jidctflt.c \
../jpeg-9c/jidctfst.c \
../jpeg-9c/jidctint.c \
../jpeg-9c/jmemmgr.c \
../jpeg-9c/jmemnobs.c \
../jpeg-9c/jquant1.c \
../jpeg-9c/jquant2.c \
../jpeg-9c/jutils.c 

C_DEPS += \
./jpeg-9c/jaricom.d \
./jpeg-9c/jcapimin.d \
./jpeg-9c/jcapistd.d \
./jpeg-9c/jcarith.d \
./jpeg-9c/jccoefct.d \
./jpeg-9c/jccolor.d \
./jpeg-9c/jcdctmgr.d \
./jpeg-9c/jchuff.d \
./jpeg-9c/jcinit.d \
./jpeg-9c/jcmainct.d \
./jpeg-9c/jcmarker.d \
./jpeg-9c/jcmaster.d \
./jpeg-9c/jcomapi.d \
./jpeg-9c/jcparam.d \
./jpeg-9c/jcprepct.d \
./jpeg-9c/jcsample.d \
./jpeg-9c/jctrans.d \
./jpeg-9c/jdapimin.d \
./jpeg-9c/jdapistd.d \
./jpeg-9c/jdarith.d \
./jpeg-9c/jdatadst.d \
./jpeg-9c/jdatasrc.d \
./jpeg-9c/jdcoefct.d \
./jpeg-9c/jdcolor.d \
./jpeg-9c/jddctmgr.d \
./jpeg-9c/jdhuff.d \
./jpeg-9c/jdinput.d \
./jpeg-9c/jdmainct.d \
./jpeg-9c/jdmarker.d \
./jpeg-9c/jdmaster.d \
./jpeg-9c/jdmerge.d \
./jpeg-9c/jdpostct.d \
./jpeg-9c/jdsample.d \
./jpeg-9c/jdtrans.d \
./jpeg-9c/jerror.d \
./jpeg-9c/jfdctflt.d \
./jpeg-9c/jfdctfst.d \
./jpeg-9c/jfdctint.d \
./jpeg-9c/jidctflt.d \
./jpeg-9c/jidctfst.d \
./jpeg-9c/jidctint.d \
./jpeg-9c/jmemmgr.d \
./jpeg-9c/jmemnobs.d \
./jpeg-9c/jquant1.d \
./jpeg-9c/jquant2.d \
./jpeg-9c/jutils.d 

OBJS += \
./jpeg-9c/jaricom.obj \
./jpeg-9c/jcapimin.obj \
./jpeg-9c/jcapistd.obj \
./jpeg-9c/jcarith.obj \
./jpeg-9c/jccoefct.obj \
./jpeg-9c/jccolor.obj \
./jpeg-9c/jcdctmgr.obj \
./jpeg-9c/jchuff.obj \
./jpeg-9c/jcinit.obj \
./jpeg-9c/jcmainct.obj \
./jpeg-9c/jcmarker.obj \
./jpeg-9c/jcmaster.obj \
./jpeg-9c/jcomapi.obj \
./jpeg-9c/jcparam.obj \
./jpeg-9c/jcprepct.obj \
./jpeg-9c/jcsample.obj \
./jpeg-9c/jctrans.obj \
./jpeg-9c/jdapimin.obj \
./jpeg-9c/jdapistd.obj \
./jpeg-9c/jdarith.obj \
./jpeg-9c/jdatadst.obj \
./jpeg-9c/jdatasrc.obj \
./jpeg-9c/jdcoefct.obj \
./jpeg-9c/jdcolor.obj \
./jpeg-9c/jddctmgr.obj \
./jpeg-9c/jdhuff.obj \
./jpeg-9c/jdinput.obj \
./jpeg-9c/jdmainct.obj \
./jpeg-9c/jdmarker.obj \
./jpeg-9c/jdmaster.obj \
./jpeg-9c/jdmerge.obj \
./jpeg-9c/jdpostct.obj \
./jpeg-9c/jdsample.obj \
./jpeg-9c/jdtrans.obj \
./jpeg-9c/jerror.obj \
./jpeg-9c/jfdctflt.obj \
./jpeg-9c/jfdctfst.obj \
./jpeg-9c/jfdctint.obj \
./jpeg-9c/jidctflt.obj \
./jpeg-9c/jidctfst.obj \
./jpeg-9c/jidctint.obj \
./jpeg-9c/jmemmgr.obj \
./jpeg-9c/jmemnobs.obj \
./jpeg-9c/jquant1.obj \
./jpeg-9c/jquant2.obj \
./jpeg-9c/jutils.obj 

OBJS__QUOTED += \
"jpeg-9c\jaricom.obj" \
"jpeg-9c\jcapimin.obj" \
"jpeg-9c\jcapistd.obj" \
"jpeg-9c\jcarith.obj" \
"jpeg-9c\jccoefct.obj" \
"jpeg-9c\jccolor.obj" \
"jpeg-9c\jcdctmgr.obj" \
"jpeg-9c\jchuff.obj" \
"jpeg-9c\jcinit.obj" \
"jpeg-9c\jcmainct.obj" \
"jpeg-9c\jcmarker.obj" \
"jpeg-9c\jcmaster.obj" \
"jpeg-9c\jcomapi.obj" \
"jpeg-9c\jcparam.obj" \
"jpeg-9c\jcprepct.obj" \
"jpeg-9c\jcsample.obj" \
"jpeg-9c\jctrans.obj" \
"jpeg-9c\jdapimin.obj" \
"jpeg-9c\jdapistd.obj" \
"jpeg-9c\jdarith.obj" \
"jpeg-9c\jdatadst.obj" \
"jpeg-9c\jdatasrc.obj" \
"jpeg-9c\jdcoefct.obj" \
"jpeg-9c\jdcolor.obj" \
"jpeg-9c\jddctmgr.obj" \
"jpeg-9c\jdhuff.obj" \
"jpeg-9c\jdinput.obj" \
"jpeg-9c\jdmainct.obj" \
"jpeg-9c\jdmarker.obj" \
"jpeg-9c\jdmaster.obj" \
"jpeg-9c\jdmerge.obj" \
"jpeg-9c\jdpostct.obj" \
"jpeg-9c\jdsample.obj" \
"jpeg-9c\jdtrans.obj" \
"jpeg-9c\jerror.obj" \
"jpeg-9c\jfdctflt.obj" \
"jpeg-9c\jfdctfst.obj" \
"jpeg-9c\jfdctint.obj" \
"jpeg-9c\jidctflt.obj" \
"jpeg-9c\jidctfst.obj" \
"jpeg-9c\jidctint.obj" \
"jpeg-9c\jmemmgr.obj" \
"jpeg-9c\jmemnobs.obj" \
"jpeg-9c\jquant1.obj" \
"jpeg-9c\jquant2.obj" \
"jpeg-9c\jutils.obj" 

C_DEPS__QUOTED += \
"jpeg-9c\jaricom.d" \
"jpeg-9c\jcapimin.d" \
"jpeg-9c\jcapistd.d" \
"jpeg-9c\jcarith.d" \
"jpeg-9c\jccoefct.d" \
"jpeg-9c\jccolor.d" \
"jpeg-9c\jcdctmgr.d" \
"jpeg-9c\jchuff.d" \
"jpeg-9c\jcinit.d" \
"jpeg-9c\jcmainct.d" \
"jpeg-9c\jcmarker.d" \
"jpeg-9c\jcmaster.d" \
"jpeg-9c\jcomapi.d" \
"jpeg-9c\jcparam.d" \
"jpeg-9c\jcprepct.d" \
"jpeg-9c\jcsample.d" \
"jpeg-9c\jctrans.d" \
"jpeg-9c\jdapimin.d" \
"jpeg-9c\jdapistd.d" \
"jpeg-9c\jdarith.d" \
"jpeg-9c\jdatadst.d" \
"jpeg-9c\jdatasrc.d" \
"jpeg-9c\jdcoefct.d" \
"jpeg-9c\jdcolor.d" \
"jpeg-9c\jddctmgr.d" \
"jpeg-9c\jdhuff.d" \
"jpeg-9c\jdinput.d" \
"jpeg-9c\jdmainct.d" \
"jpeg-9c\jdmarker.d" \
"jpeg-9c\jdmaster.d" \
"jpeg-9c\jdmerge.d" \
"jpeg-9c\jdpostct.d" \
"jpeg-9c\jdsample.d" \
"jpeg-9c\jdtrans.d" \
"jpeg-9c\jerror.d" \
"jpeg-9c\jfdctflt.d" \
"jpeg-9c\jfdctfst.d" \
"jpeg-9c\jfdctint.d" \
"jpeg-9c\jidctflt.d" \
"jpeg-9c\jidctfst.d" \
"jpeg-9c\jidctint.d" \
"jpeg-9c\jmemmgr.d" \
"jpeg-9c\jmemnobs.d" \
"jpeg-9c\jquant1.d" \
"jpeg-9c\jquant2.d" \
"jpeg-9c\jutils.d" 

C_SRCS__QUOTED += \
"../jpeg-9c/jaricom.c" \
"../jpeg-9c/jcapimin.c" \
"../jpeg-9c/jcapistd.c" \
"../jpeg-9c/jcarith.c" \
"../jpeg-9c/jccoefct.c" \
"../jpeg-9c/jccolor.c" \
"../jpeg-9c/jcdctmgr.c" \
"../jpeg-9c/jchuff.c" \
"../jpeg-9c/jcinit.c" \
"../jpeg-9c/jcmainct.c" \
"../jpeg-9c/jcmarker.c" \
"../jpeg-9c/jcmaster.c" \
"../jpeg-9c/jcomapi.c" \
"../jpeg-9c/jcparam.c" \
"../jpeg-9c/jcprepct.c" \
"../jpeg-9c/jcsample.c" \
"../jpeg-9c/jctrans.c" \
"../jpeg-9c/jdapimin.c" \
"../jpeg-9c/jdapistd.c" \
"../jpeg-9c/jdarith.c" \
"../jpeg-9c/jdatadst.c" \
"../jpeg-9c/jdatasrc.c" \
"../jpeg-9c/jdcoefct.c" \
"../jpeg-9c/jdcolor.c" \
"../jpeg-9c/jddctmgr.c" \
"../jpeg-9c/jdhuff.c" \
"../jpeg-9c/jdinput.c" \
"../jpeg-9c/jdmainct.c" \
"../jpeg-9c/jdmarker.c" \
"../jpeg-9c/jdmaster.c" \
"../jpeg-9c/jdmerge.c" \
"../jpeg-9c/jdpostct.c" \
"../jpeg-9c/jdsample.c" \
"../jpeg-9c/jdtrans.c" \
"../jpeg-9c/jerror.c" \
"../jpeg-9c/jfdctflt.c" \
"../jpeg-9c/jfdctfst.c" \
"../jpeg-9c/jfdctint.c" \
"../jpeg-9c/jidctflt.c" \
"../jpeg-9c/jidctfst.c" \
"../jpeg-9c/jidctint.c" \
"../jpeg-9c/jmemmgr.c" \
"../jpeg-9c/jmemnobs.c" \
"../jpeg-9c/jquant1.c" \
"../jpeg-9c/jquant2.c" \
"../jpeg-9c/jutils.c" 


